#!/bin/bash

echo "=========================================="
echo "iOS Production Build Setup for Nuolo"
echo "=========================================="
echo ""
echo "This script will help you set up iOS credentials for production builds."
echo ""
echo "Prerequisites:"
echo "✓ Apple Developer Account (you have this)"
echo "✓ Apple ID and password ready"
echo "✓ Two-factor authentication enabled on your Apple ID"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Step 1: Configuring EAS Credentials"
echo "------------------------------------"
echo "You'll be asked to:"
echo "1. Select 'iOS' platform"
echo "2. Choose 'Build Credentials for com.nuolo.app'"
echo "3. Select 'Set up a new Apple Developer account' or 'Use existing'"
echo "4. Enter your Apple ID email"
echo "5. Enter your Apple ID password"
echo "6. Enter 2FA code when prompted"
echo ""
echo "Starting credential setup..."
echo ""

npx eas credentials --platform ios

echo ""
echo "Step 2: Creating App on App Store Connect"
echo "-----------------------------------------"
echo "While the build is running, please:"
echo "1. Go to https://appstoreconnect.apple.com/"
echo "2. Click 'My Apps' → '+' → 'New App'"
echo "3. Use these details:"
echo "   - Platform: iOS"
echo "   - Name: Nuolo Audio Tour Guide"
echo "   - Primary Language: English (U.S.)"
echo "   - Bundle ID: com.nuolo.app"
echo "   - SKU: nuolo-app-001"
echo "   - User Access: Full Access"
echo ""
echo "Press Enter once you've created the app on App Store Connect..."
read

echo ""
echo "Step 3: Building for Production"
echo "--------------------------------"
echo "Now we'll start the production build."
echo "This will create a build that can be submitted to the App Store."
echo ""
echo "Starting production build..."
echo ""

npx eas build --platform ios --profile production

echo ""
echo "=========================================="
echo "Build Started!"
echo "=========================================="
echo ""
echo "The build is now running on EAS servers."
echo "You can monitor progress at the URL shown above."
echo ""
echo "Once the build completes (15-30 minutes), run:"
echo "npx eas submit --platform ios --latest"
echo ""
echo "This will upload your app to TestFlight for testing."
echo ""